Add option for matching a file to be transformed
shixuanhong/vite-plugin-css-export pull request #3
Opened 2022-11-12 02:24 UTC by Fattimo

2022-11-12 02:27 UTC, Fattimo commented
resolves #2

2022-11-12 13:55 UTC, shixuanhong requested changes

2022-11-12 13:55 UTC, shixuanhong commented on src/index.ts
> +      if (isCSSRequest(id) && shouldTransform ? (shouldTransform(id) : exportRE?.test(id))) {
This expression doesn't seem to work properly

2022-11-12 13:55 UTC, shixuanhong commented on src/index.ts
> +      if (isCSSRequest(id) && options.shouldTransform ? (options.shouldTransform(id) : exportRE?.test(id))) {
same as that

2022-11-12 18:47 UTC, Fattimo commented
sorry about that! I was not at my usual laptop and thought using the github editor would be simple enough.

I've gone ahead and made the code actually functional 😅 and updated the documentation + example. Let me know if there are any other blockers for this feature

2022-11-12 18:49 UTC, Fattimo commented
<img width="542" alt="image" src="https://user-images.githubusercontent.com/57023314/201489976-e3f98c00-8df6-4c32-a065-c8dad4c906ac.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/57023314/201490016-24507f6b-0115-436a-9102-a5d92668738f.png">

2022-11-14 17:35 UTC, shixuanhong commented on src/index.ts
> +      if (isCSSRequest(id) && shouldTransform ? shouldTransform(id) : exportRE?.test(id)) {
Maybe you don't understand what I mean, I prefer both to work, not just one or the other. (#2 )

Like  `shouldTransform(id) || exportRE.test(id) `

2022-11-14 17:35 UTC, shixuanhong commented on client.d.ts
> +declare module '*.scss?shouldTransformString' {
If you are just writing an example, please do not modify this file, it may be referenced by users.

2022-11-14 17:36 UTC, closed without merging